### ISSUE TITLE
OpenCPU Response => 'Resource temporarily unavailable'

### ISSUE THREAD

**Issue by capiisco** [jeroen/opencpu#227]
Hello,

I send requests opencpu and I have systematically the following error :

cannot popen '/usr/bin/which 'uname' 2>/dev/null', probable reason 'Resource temporarily unavailable'

In call:
system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)

OS => Red Hat Enterprise Linux VERSION=7.0

My Opencpu Install => yum install –y opencpu-lib-1.5.3-rpm0.x86_64.rpm rapache-1.2.7-rpm0.x86_64.rpm opencpu-server-1.5.3-rpm0.x86_64.rpm rapache-debuginfo-1.2.7-rpm0.x86_64.rpm
	  
Memory :	  
]$ free -h
              total        used        free      shared  buff/cache   available
Mem:            61G        2.3G         56G         24M        2.5G         58G
Swap:           11G          0B         11G

Disk Space :
]$ df -h .
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   97G  8.4G   89G   9% /

How to avoid this problem definitively ?

Thank.

**Comment by jeroen** [comment]
That's odd. Few things you can try:

 - Increase `rlimit.nproc` inside `/etc/opencpu/server.conf` and run `sudo apache2 restart`
 - Enable the apache2 `prefork` module

Also note that the 1.5 branch is old. Current is 1.6 and I'm about to release 2.0. So maybe updating helps.

**Comment by jeroen** [comment]
Did this solve your problem?

**Comment by capiisco** [comment]
Thank , it works now. I'll upgrade it to 1.6
Good job
